# Normal subgroups of the prescribed extraspecial subgroup E and subgroup
# classes in the orthogonal quotient.

GF316CoreFormData := function(coreMatrices)
    local F2, F3, V, identity, commutatorForm, i, j, commutator,
          row, quadraticValues, v, word;
    F2 := GF(2);;
    F3 := GF(3);;
    V := F2^8;;
    identity := IdentityMat(16, F3);;
    commutatorForm := [];;
    for i in [1 .. 8] do
        row := [];;
        for j in [1 .. 8] do
            commutator := coreMatrices[i]^-1 * coreMatrices[j]^-1
                * coreMatrices[i] * coreMatrices[j];;
            if commutator = identity then
                Add(row, Zero(F2));
            elif commutator = -identity then
                Add(row, One(F2));
            else
                Error("a commutator of the chosen generators of E is neither I nor -I");
            fi;
        od;
        Add(commutatorForm, row);
    od;
    Assert(0, RankMat(commutatorForm) = 8);;

    quadraticValues := ListWithIdenticalEntries(256, fail);;
    for v in AsList(V) do
        word := identity;;
        for i in [1 .. 8] do
            if v[i] = One(F2) then
                word := word * coreMatrices[i];
            fi;
        od;
        if word^2 = identity then
            quadraticValues[NumberFFVector(v, 2) + 1] := 0;
        elif word^2 = -identity then
            quadraticValues[NumberFFVector(v, 2) + 1] := 1;
        else
            Error("a chosen representative of E/Z(E) has a square other than I or -I");
        fi;
    od;
    Assert(0, not fail in quadraticValues);;
    return rec(
        field := F2,
        space := V,
        zero := Zero(V),
        commutatorForm := commutatorForm,
        quadraticValues := quadraticValues);
end;;

GF316GeneratedSubmodule := function(H, v, V)
    local U, rows, images, u, g, next;
    U := Subspace(V, [ v ]);;
    repeat
        rows := BasisVectors(Basis(U));;
        images := ShallowCopy(rows);;
        for u in rows do
            for g in GeneratorsOfGroup(H) do
                Add(images, u * g);
            od;
        od;
        next := Subspace(V, images);;
        if Dimension(next) = Dimension(U) then
            return U;
        fi;
        U := next;
    until false;
end;;

GF316FormValue := function(data, u, v)
    local value, i, j;
    value := Zero(data.field);;
    for i in [1 .. 8] do
        for j in [1 .. 8] do
            value := value + u[i] * data.commutatorForm[i][j] * v[j];
        od;
    od;
    return value;
end;;

# If U is invariant and D is its preimage in E, then D acts homogeneously
# exactly when rad(B|U) is zero or is a one-dimensional anisotropic line.
# A singular radical vector lifts to a noncentral central involution with two
# nonzero eigenspaces.  The quadratic form is linear on a radical, so a bad
# invariant radical contains a singular vector.  The cyclic submodule
# generated by that vector remains in the radical; testing all 255 nonzero
# vectors therefore tests every possible bad invariant subspace.

GF316CoreNormalTest := function(H, data)
    local seen, v, U, rows, key, gram, radical, radicalVector, i;
    seen := NewDictionary("", true);;
    for v in AsList(data.space) do
        if v = data.zero then
            continue;
        fi;
        U := GF316GeneratedSubmodule(H, v, data.space);;
        rows := BasisVectors(Basis(U));;
        key := String(rows);;
        if LookupDictionary(seen, key) = fail then
            AddDictionary(seen, key, true);;
            gram := List(rows,
                u -> List(rows, w -> GF316FormValue(data, u, w)));;
            radical := NullspaceMat(gram);;
            if Length(radical) > 1 then
                return false;
            fi;
            if Length(radical) = 1 then
                radicalVector := Sum([1 .. Length(rows)],
                    i -> radical[1][i] * rows[i]);;
                if data.quadraticValues[
                    NumberFFVector(radicalVector, 2) + 1] = 0 then
                    return false;
                fi;
            fi;
        fi;
    od;
    return true;
end;;

GF316PreimageSubgroup := function(iso, domain, H)
    local generators;
    generators := List(GeneratorsOfGroup(H),
        x -> PreImagesRepresentative(iso, x));;
    if Length(generators) = 0 then
        return TrivialSubgroup(domain);
    fi;
    return Group(generators);
end;;

GF316ImageSubgroup := function(iso, codomain, H)
    local generators;
    generators := List(GeneratorsOfGroup(H), x -> Image(iso, x));;
    if Length(generators) = 0 then
        return TrivialSubgroup(codomain);
    fi;
    return Group(generators);
end;;

GF316QuasiprimitiveQuotients := function(sign, quotient, coreMatrices,
    liftSubgroup, expectedAll, expectedSolvable, expectedCorrected,
    expectedExact)
    local standard, toPermutation, permutationGroup, toQuotient, allClasses,
          solvableClasses, survivors, position, Kp, Kstandard, K,
          keep, allCount, solvableCount, correctedCount, r, H, irreducible,
          quasiprimitive, exactSurvivors, data;

    data := GF316CoreFormData(coreMatrices);;
    standard := GO(sign, 8, 2);;
    Assert(0, Size(standard) = Size(quotient));;
    toPermutation := IsomorphismPermGroup(standard);;
    permutationGroup := Image(toPermutation);;
    toQuotient := IsomorphismGroups(standard, quotient);;
    if toQuotient = fail then
        Error("the constructed orthogonal quotient was not identified");
    fi;

    allClasses := ConjugacyClassesSubgroups(permutationGroup);;
    solvableClasses := Filtered(allClasses,
        c -> IsSolvableGroup(Representative(c)));;
    allCount := Length(allClasses);;
    solvableCount := Length(solvableClasses);;
    Assert(0, allCount = expectedAll);;
    Assert(0, solvableCount = expectedSolvable);;

    survivors := [];;
    for position in [1 .. solvableCount] do
        Kp := Representative(solvableClasses[position]);;
        Kstandard := GF316PreimageSubgroup(toPermutation, standard, Kp);;
        K := GF316ImageSubgroup(toQuotient, quotient, Kstandard);;
        keep := GF316CoreNormalTest(K, data);;
        if keep then
            Add(survivors, rec(
                sourceClass := position,
                quotient := K,
                quotientOrder := Size(K)));
        fi;
    od;
    correctedCount := Length(survivors);;
    Assert(0, correctedCount = expectedCorrected);;

    Unbind(allClasses);;
    Unbind(solvableClasses);;
    Unbind(permutationGroup);;
    Unbind(standard);;
    Unbind(toPermutation);;
    Unbind(toQuotient);;
    CollectGarbage(true);;

    for r in survivors do
        H := liftSubgroup(r.quotient);;
        Assert(0, Size(H) = 512 * r.quotientOrder);;
        irreducible := MTX.IsIrreducible(
            GModuleByMats(GeneratorsOfGroup(H), GF(3)));;
        quasiprimitive := irreducible
            and IsQuasiprimitiveLinearGroup(H, 3, 16);;
        r.exact := irreducible and quasiprimitive;;
        Unbind(H);;
    od;
    exactSurvivors := Filtered(survivors, r -> r.exact);;
    Assert(0, Length(exactSurvivors) = expectedExact);;
    return rec(
        subgroupClassCount := allCount,
        solvableClassCount := solvableCount,
        correctedCoreNormalCount := correctedCount,
        exactCount := Length(exactSurvivors),
        survivors := exactSurvivors);
end;;
